### ISSUE TITLE
File Size Limit on Email Attachments

### ISSUE THREAD

**Issue by terminator14** [pinax/django-mailer#121] opened 2020-03-03 18:35 UTC
**Describe the bug**
I have a project using django 2.2.4, and django-mailer 2.0.1 from pypi. The default django backend has no issues sending big attachments, but django-mailer seems to cause MySQL to disconnect for some reason when the attachment is bigger than a few hundred KB.

**Reproduce behavior**
I did this on Linux:

```
# Create test files:
$ mkdir /tmp/files
$ cd /tmp/files
$ for i in $(seq 680 5 900); do echo ${i}KB; dd if=/dev/urandom of=${i}KB bs=1K count=$i; sync; done

$ /opt/project_dir/manage.py shell
from django.core.mail import EmailMessage
for i in range(680, 901, 5):
	print(f"Sending file /tmp/files/{i}KB")
	message = EmailMessage(
		subject="Test Subject",
		body="Test Body",
		from_email="Test From Header",
		to=["some_email@domain.com"])
	message.attach_file(f"/tmp/files/{i}KB")
	message.send()
```

It sends the first few, and throws an exception that the MySQL server disconnected. 
Disabling django-mailer in settings.py, and letting it use the default django backend fixes the problem.

I also tried:

- message.attach() instead of message.attach_file()
- reusing a connection with `connection = mail.get_connection()`

Both throw the exact same error.

**Desktop**
 - OS: CentOS 7

This code is being run by a background process that monitors for, and sends out notifications. My background process imports my django models, and uses the django ORM directly.

I got around this by just using `connection = mail.get_connection(backend="django.core.mail.backends.smtp.EmailBackend")` in this background process to use the default django backend, and using django-mailer in the main process that handles client requests.

I don't have a ton of time to get more info on this at the moment, but if someone can reproduce, that would be great. If not, let me know and I'll try to find some time to gather more info.

**Comment by spookylukey** [comment] 2020-03-04 05:53
This is very unlikely to be a bug in django-mailer. More likely it is a limit in your MySQL configuration - see this: https://stackoverflow.com/questions/16335011/what-is-maximum-query-size-for-mysql . By it's very nature django-mailer has to send data to the database via a query so there is no other way around this as far as I can see.

Since there is nothing we can do about this at the level of django-mailer, so I'm closing this now. If my guess is wrong and there is a genuine issue in django-mailer please re-open this bug. If you'd like to add a documentation patch to django-mailer warning about this, it would be accepted.

**Closed** 2020-03-04 05:53 UTC
Labels: bug

**Comment by terminator14** [comment] 2020-03-04 15:53
Oh - I see. I know that when django requests an email be sent, django-mailer's backend just writes to the database, and a background process, usually run by cron, reads from the database and sends the email.

I guess it never occurred to me that if you're sending an attachment, the entire file is also stored in the database, and is subject to database query limitations.

This seems like a pretty big limitation for those sending files, and one that causes errors that are hard to debug. When sending an email with an attachment, it was very unclear why Python was throwing a MySQL error. It wasn't even clear that the file size was the problem, or that django-mailer was somehow responsible for this.

I know that one could argue that this is the database's configuration limit, but as far as I know, databases are not designed to store huge binary data. This to me sounds like a design flaw with django-mailer - not a database problem.

As a short-term solution, I would suggest either making this limitation clear in the README.rst, or adding some kind of check to django mailer that when a file is large, it throws its own exception that is more clear, and skips the file, rather than waiting for the database to disconnect, throwing a seemingly unrelated exception.

As a long-term solution, I would suggest looking into some kind of a way to store files (attachments) on the filesystem, rather than in the database. Not sure how difficult this is, but it seems like it's a pretty important feature.

**Comment by spookylukey** [comment] 2020-03-05 05:32
Sorry, I thought it was obvious from the README that this was how django-mailer worked, but I've added a note [right at the top](https://github.com/pinax/django-mailer/blob/master/README.rst#django-mailer-1) now that makes it clear.

Storing files on the filesystem is not an option, because for Django projects in general we have no guarantee that we will be able to use the filesystem. If you have multiple Django instances spread over multiple boxes, they will have distinct file systems, so won't be able to access each others files. That's why a database is a good option, because it is a shared resource, and it's the only shared resource you can really count on in Django projects.

We could use other things, like S3 buckets etc, or indeed could use the filesystem in some cases. But making django-mailer flexible enough to use all of these would be a very large job, and quite out of scope for the size of a small tool like this.

While we can add specific docs and warnings for the problems different databases may face, I'm not inclined to add specific error handling - it is a generic problem with executing large queries and MySQL, not one specific to django-mailer. There are plenty of other apps that store this kind of data in a database, even if it isn't ideal, because you often don't have other good options. The stacktrace should have pointed to django-mailer as the source of the error, and that's all you can really do. There are so many database level issues you can have, it's better to just let the stracktrace show the problem.

**Comment by terminator14** [comment] 2020-03-05 22:55
Ok - makes sense.

For the record, this is what the stacktrace looks like:

```
>>> from django.core import mail
>>> message = mail.EmailMessage("Subject", "Body", "from", ["some_email@gmail.com"])
>>> message.attach_file("/my/big/file")
>>> message.send()
Traceback (most recent call last):
  File "/opt/my_project/venv3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/my_project/venv3/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/opt/my_project/venv3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/opt/my_project/venv3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/opt/my_project/venv3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 226, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (2006, 'MySQL server has gone away')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/opt/my_project/venv3/lib64/python3.6/site-packages/django/core/mail/message.py", line 291, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/opt/my_project/venv3/lib64/python3.6/site-packages/mailer/backend.py", line 17, in send_messages
    ], MESSAGES_BATCH_SIZE)
  File "/opt/my_project/venv3/lib64/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/my_project/venv3/lib64/python3.6/site-packages/django/db/models/query.py", line 474, in bulk_create
    ids = self._batched_insert(objs_without_pk, fields, batch_size, ignore_conflicts=ignore_conflicts)
  File "/opt/my_project/venv3/lib64/python3.6/site-packages/django/db/models/query.py", line 1211, in _batched_insert
    self._insert(item, fields=fields, using=self.db, ignore_conflicts=ignore_conflicts)
  File "/opt/my_project/venv3/lib64/python3.6/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/opt/my_project/venv3/lib64/python3.6/site-packages/django/db/models/sql/compiler.py", line 1368, in execute_sql
    cursor.execute(sql, params)
  File "/opt/my_project/venv3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/opt/my_project/venv3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/opt/my_project/venv3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/opt/my_project/venv3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/my_project/venv3/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/opt/my_project/venv3/lib64/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/my_project/venv3/lib64/python3.6/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "/opt/my_project/venv3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 209, in execute
    res = self._query(query)
  File "/opt/my_project/venv3/lib64/python3.6/site-packages/MySQLdb/cursors.py", line 315, in _query
    db.query(q)
  File "/opt/my_project/venv3/lib64/python3.6/site-packages/MySQLdb/connections.py", line 226, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (2006, 'MySQL server has gone away')

```

If there's an indication somewhere that this is a django_mailer error, I don't see it. I'm sure lots of others won't either.

**Comment by spookylukey** [comment] 2020-03-06 18:26
It's here:
```
File "/opt/my_project/venv3/lib64/python3.6/site-packages/django/core/mail/message.py", line 291, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/opt/my_project/venv3/lib64/python3.6/site-packages/mailer/backend.py", line 17, in send_messages
    ], MESSAGES_BATCH_SIZE)
```
The first line shows that the error happens when Django is trying to send mail, and the second line shows that we've moved to the `mailer` module to actually send the mail, which is the Python module for django-mailer. (Unfortunately it doesn't say `django_mailer`, but `mailer`, and, again unfortunately, that's not a choice I can change now, and it's the case with many Python packages that the PyPI package name is not the same as the top level module).

If you work your way through the stacktrace from bottom up, you can see all the modules that are involved. It contains lots of lines that aren't django_mailer, but that's how stacktraces work, you have to look through and see what is generating the query. In this case, the line pointed to in `mailer` is  https://github.com/pinax/django-mailer/blob/5992fff2637632e69493ca0910e4a28ce62c4b0a/src/mailer/backend.py#L17 is a Django `bulk_create` call which is the ultimate source of the DB query.

If I tried to add special error handling, I'd have to add something that catches the `django.db.utils.OperationalError`, and prints an error message about email/query size. The problem is, this would also catch a vast array of other problems, because `OperationalError` could be triggered in completely different scenarios, which might have completely different causes, and it would then print a completely unhelpful hint that might actually send you off on the wrong direction. Plus it would make the stracktrace even harder to understand, because each `except` adds another section to it.

That's why I think I that adding some documentation about this is far more helpful (thanks for your PR!). I'm not trying to blow you off, I'm explaining why 'fixes' that try to address this one issue can be counter-productive. I'm sorry django-mailer wasted your time, thanks again for your documentation patch.

**Comment by nautatva** [comment] 2020-08-20 18:48
I couldn't find any documentation on how do we add attachments. Can someone please help me with some references.

**Comment by terminator14** [comment] 2020-08-21 03:21
@nautatva your question is unrelated to this issue, so I sent you an email reply.
