### ISSUE TITLE
Lockfile can't install.

### ISSUE THREAD

**Issue by andrewfam** [pinax/django-mailer#61] opened 2016-06-02 07:27 UTC
I'm getting an import error on the pip install of lockfile

        return self.build_and_install(setup_script, setup_base)
      File "/webapps/dpms/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1130, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/webapps/dpms/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1115, in run_setup
        run_setup(setup_script, args)
      File "/webapps/dpms/lib/python2.7/site-packages/setuptools/sandbox.py", line 69, in run_setup
        lambda: execfile(
      File "/webapps/dpms/lib/python2.7/site-packages/setuptools/sandbox.py", line 120, in run
        return func()
      File "/webapps/dpms/lib/python2.7/site-packages/setuptools/sandbox.py", line 71, in <lambda>
        {'__file__':setup_script, '__name__':'__main__'}
      File "setup.py", line 22, in <module>
        try:
      File "/tmp/easy_install-bIbCye/pbr-1.10.0/pbr/util.py", line 264, in cfg_to_args
      File "/tmp/easy_install-bIbCye/pbr-1.10.0/pbr/util.py", line 573, in wrap_commands
      File "/webapps/dpms/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
        entry = __import__(self.module_name, globals(),globals(), ['__name__'])
    ImportError: No module named build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

Anyway to not use the lockfile

**Comment by spookylukey** [comment] 2016-06-04 11:17
I can't reproduce a problem installing lockfile (tried using Python 2.7 and 3.4), and I can't see that the error above is to do with lockfile (you've only posted part of the error message, and didn't include any details about what steps you took to produce that error). Anyway, this repo is django-mailer, not lockfile. If there is an issue with lockfile, you should file a bug on their bug tracker. Otherwise, I'm afraid I don't understand what you are asking or saying.

So I'm going to close this. If you can provide more information about what the problem with django-mailer is, please re-open.

Thanks!

**Closed by spookylukey** 2016-06-04 11:17 UTC
Labels: bug, question

**Comment by andrewfam** [comment] 2016-06-07 13:57
@spookylukey Hey not too sure why on centos 7, I had to downgrad to lockfile 0.8 for it to work. .9, .10, .11 doesn't work
